# Actividad - Estadística básica

* **Nombre:Javier Hurtado**
* **Matrícula:A01254039**

**Entregar:** Archivo PDF de la actividad, así como el archivo .ipynb en tu repositorio.
**Nota:** Recuerda habrá una penalización de **50** puntos si la actividad fue entregada fuera de la fecha límite.

Carga el conjunto de datos `insurance.csv` (se encuentra en el repositorio de la clase) y realiza un análisis estadístico de las variables.

In [5]:
import pandas as pd
import numpy as np
import random

In [7]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving insurance.csv to insurance.csv
User uploaded file "insurance.csv" with length 55628 bytes

In [8]:
df = pd.read_csv('insurance.csv')
df.head(6)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160

El conjunto de datos contiene información demográfica sobre los asegurados en una compañía de seguros:
* **age**: Edad del asegurado principal
* **sex**: Género del asegurado. female o male
* **bmi**: Índice de masa corporal
* **children**: Número de hijos que estan cubiertos con la poliza. 
* **smoke**: ¿El beneficiario fuma? (*yes*/*no*)
* **region**: ¿Dónde vive el beneficiario? Estos datos son de Estados Unidos. Regiones disponibles: northeast, southeast, southwest, northwest
* **charges**: Costo del seguro.

In [ ]:
# Crea una tabla resumen con los estadísticas generales de las variables
# numéricas.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
# ¿Cómo se correlacionan las varaibles numéricas entre sí?

In [11]:
df.corr()

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [ ]:
# Determina si existe o no una correlación entre el índice de masa corporal 
# (bmi) y el costo del seguro.

In [12]:
df.corr()

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

Por lo visto la correlacion es minima, pues es solo de 0.2.

In [ ]:
# ¿Cuántas personas aseguradas son hombre y cuántas son mujeres?

In [10]:
df['sex'].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [ ]:
# ¿Cuántos hombres y mujeres asegurados viven en cada región?

In [11]:
pd.crosstab(df['region'], df['sex'])

sex        female  male
region
northeast     161   163
northwest     164   161
southeast     175   189
southwest     162   163

In [ ]:
# En promedio, ¿quién paga más de cuota de seguro? ¿Los fumadores o los no 
# fumadores? Muéstralo con los datos.

In [13]:
df.groupby('smoker').mean()[['charges']]

             charges
smoker
no       8434.268298
yes     32050.231832

In [ ]:
# ¿Cuáles son las cuotas mínimas y máximas que las personan pagan dependiendo
# del género y del número de hijos?

In [14]:
df.groupby(['sex', 'children']).agg(['min', 'max'])[['charges']]

                    charges
                        min          max
sex    children
female 0         1607.51010  63770.42801
       1         2201.09710  58571.07448
       2         2801.25880  47305.30500
       3         4234.92700  46661.44240
       4         4561.18850  36580.28216
       5         4687.79700  19023.26000
male   0         1121.87390  62592.87309
       1         1711.02680  51194.55914
       2         2304.00220  49577.66240
       3         3443.06400  60021.39897
       4         4504.66240  40182.24600
       5         4915.05985  14478.33015

In [ ]:
# ¿Cuál es el índice de masa corporal promedio para hombre y mujeres dependiendo
# región en la que viven y si son fumadores? ¿Impacta eso en la tarifa del 
# seguro?

In [10]:
df.groupby(['sex', 'smoker', 'region']).mean()[['bmi']]

                               bmi
sex    smoker region
female no     northeast  29.777462
              northwest  29.488704
              southeast  32.780000
              southwest  30.050355
       yes    northeast  27.261724
              northwest  28.296897
              southeast  32.251389
              southwest  30.128571
male   no     northeast  28.861760
              northwest  28.930379
              southeast  34.129552
              southwest  31.019841
       yes    northeast  29.560000
              northwest  29.983966
              southeast  33.650000
              southwest  31.502703

Realmente no se ve un impacto significativo en cuanto a las tarifas, si bien hay un cambio minusculo no afecta tanto como se esperaria.